# Inserts a blank line between shell prompts
add_newline = true

# Change the default prompt format
format = """\
[╭╴](238)$env_var \
$all[╰─](238)$character"""

[character]
success_symbol = "[](238)"
error_symbol = "[](238)"

[env_var.STARSHIP_SYSTEM]
format = '[$env_value](white)'
variable = "STARSHIP_SYSTEM"
disabled = false

[username]
style_user = "#12191f"
style_root = "#ef2152"
format = "on [ $user]($style) "
disabled = false
show_always = true

[directory]
truncation_length = 0
truncate_to_repo = false
use_os_path_sep = false
home_symbol = " ~"
read_only_style = "#ef2152"
read_only = "  "
format = "at [$path]($style)[$read_only]($read_only_style) "
style = "#12191f"

[git_branch]
format = "on [$symbol$branch]($style) "
truncation_length = 4
truncation_symbol = "…/"
style = "#12191f"

[git_status]
format = '[\( $all_status$ahead_behind \)]($style) '
conflicted = "🏳"
up_to_date = ""
untracked = ""
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
stashed = ""
modified = ""
staged = '[+$count](#12191f)'
renamed = "襁"
deleted = ""
style = "#12191f"

[python]
symbol = " "
style = "#12191f"
python_binary = ["./venv/Scripts/python", "python", "python3", "python2"]

[nodejs]
symbol = " "
style = "#12191f"

[java]
symbol = " "
style = "#12191f"

[package]
symbol = ""
style = "#12191f"
display_private = true
