# Inserts a blank line between shell prompts
add_newline = true

# Change the default prompt format
format = """\
[??](238)$env_var\
$all[?-](238)$character"""

[character]
success_symbol = "[?](238)"
error_symbol = "[?](238)"

[env_var.STARSHIP_SYSTEM]
format = '[$env_value](bold white)'
variable = "STARSHIP_SYSTEM"
disabled = false

[username]
style_user = "white bold"
style_root = "red bold"
format = "[$user]($style) "
disabled = false
show_always = false

[directory]
truncation_length = 3
truncation_symbol = "…/"
home_symbol = "?"
read_only_style = "197"
read_only = " ? "
format = "at [$path]($style)[$read_only]($read_only_style) "

[git_branch]
symbol = "? "
format = "on [$symbol$branch]($style) "
truncation_length = 4
truncation_symbol = "…/"
style = "magenta"

[git_status]
format = '[\($all_status$ahead_behind\)]($style) '
style = "magenta"
conflicted = "??"
up_to_date = "? "
untracked = "? "
ahead = "?${count}"
diverged = "??${ahead_count}?${behind_count}"
behind = "?${count}"
stashed = "? "
modified = "? "
staged = '[++\($count\)](magenta)'
renamed = "? "
deleted = "? "

[python]
symbol = "? "

[nodejs]
format = "via [? $version](magenta) "
