# Inserts a blank line between shell prompts
add_newline = true

# Change the default prompt format
format = """\
[╭╴](238)$env_var \
$all[╰─](238)$character"""

[character]
success_symbol = "[](238)"
error_symbol = "[](238)"

[env_var.STARSHIP_SYSTEM]
format = '[$env_value](white)'
variable = "STARSHIP_SYSTEM"
disabled = false

[aws]
format = "on [$symbol $profile]($style) "
symbol = ""
style = "#12191f"

[azure]
format = "on [$symbol $subscription]($style) "
style = "#12191f"
disabled = false

[c]
format = "via [$symbol $name ($version )]($style)"
symbol = ""
style = "#12191f"

[cmd_duration]
style = "#12191f"

[cmake]
style = "#12191f"

[container]
format = "[$symbol $name]($style) "
symbol = ""
style = "#12191f"

[dart]
symbol = " "
style = "#12191f"

[directory]
truncation_length = 0
truncate_to_repo = false
use_os_path_sep = false
home_symbol = " ~"
read_only_style = "#ef2152"
read_only = " "
format = "at [$path]($style)[$read_only]($read_only_style) "
style = "#12191f"

[docker_context]
format = "via [$symbol $context]($style) "
symbol = ""
style = "#12191f"

[dotnet]
format = "via [$symbol ($version )]($style)"
symbol = ""
style = "#12191f"

[git_branch]
format = "on [$symbol $branch (-> $remote_branch )]($style)"
truncation_length = 8
truncation_symbol = "…"
symbol = ""
style = "#12191f"

[git_status]
format = '[\( $all_status$ahead_behind\)]($style) '
conflicted = "🏳 "
up_to_date = " "
untracked = " "
ahead = "⇡${count} "
diverged = "⇕⇡${ahead_count}⇣${behind_count} "
behind = "⇣${count} "
stashed = " "
modified = " "
staged = '[+$count](#12191f) '
renamed = "襁 "
deleted = " "
style = "#12191f"

[hostname]
format = "on [$ssh_symbol $hostname]($style) "
ssh_symbol = "爵"
trim_at = ""
style = "#12191f"

[java]
symbol = " "
style = "#12191f"

[kotlin]
symbol = " "
style = "#12191f"

[kubernetes]
format = 'on [$symbol ($user on )($cluster in )$context \($namespace\)]($style) '
symbol = "ﴱ"
style = "#12191f"
disabled = false

[nim]
symbol = " "
style = "#12191f"

[nodejs]
style = "#12191f"
not_capable_style = "#ef2152"

[package]
symbol = ""
style = "#12191f"
display_private = true

[python]
symbol = " "
style = "#12191f"
python_binary = ["./venv/Scripts/python", "python", "python3", "python2"]

[username]
style_user = "#12191f"
style_root = "#ef2152"
format = "on [ $user]($style) "
disabled = false
show_always = true